DROP DATABASE IF EXISTS primera_parte;
CREATE DATABASE primera_parte
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_spanish_ci;
    
USE primera_parte;

CREATE TABLE MEDICO (
  ID_MEDICO      INT AUTO_INCREMENT,
  NOMBRE         VARCHAR(100) NOT NULL,
  ESPECIALIDAD   VARCHAR(80),
  TELEFONO       VARCHAR(12),
  EMAIL          VARCHAR(100),
  PRIMARY KEY (ID_MEDICO)
);

CREATE TABLE PACIENTE (
  ID_PACIENTE       INT AUTO_INCREMENT,
  NOMBRE            VARCHAR(100) NOT NULL,
  FECHA_NACIMIENTO  DATE,
  GENERO            CHAR(1),
  HISTORIAL_MEDICO  TEXT,
  CONTACTO          VARCHAR(150),
  PRIMARY KEY (ID_PACIENTE)
);

CREATE TABLE OPERACION_TRASPLANTE (
  ID_OPERACION       INT AUTO_INCREMENT,
  FECHA              DATE NOT NULL,
  TIPO_PROCEDIMIENTO VARCHAR(80),
  ZONA_DONANTE       VARCHAR(60),
  ZONA_RECEPTORA     VARCHAR(60),
  ID_PACIENTE        INT,
  ID_MEDICO          INT,
  PRIMARY KEY (ID_OPERACION),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
  FOREIGN KEY (ID_MEDICO)   REFERENCES MEDICO   (ID_MEDICO)
);

CREATE TABLE CITA (
  ID_CITA      INT AUTO_INCREMENT,
  FECHA_HORA   DATETIME NOT NULL,
  MOTIVO       VARCHAR(200),
  CONFIRMACION BOOLEAN DEFAULT FALSE,
  ID_PACIENTE  INT,
  ID_MEDICO    INT,
  PRIMARY KEY (ID_CITA),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
  FOREIGN KEY (ID_MEDICO)   REFERENCES MEDICO   (ID_MEDICO)
);

CREATE TABLE VISITA_SEGUIMIENTO (
  ID_VISITA       INT AUTO_INCREMENT,
  FECHA           DATE NOT NULL,
  OBSERVACIONES   TEXT,
  RESULTADOS      TEXT,
  RECOMENDACIONES TEXT,
  ID_PACIENTE     INT,
  ID_MEDICO       INT,
  PRIMARY KEY (ID_VISITA),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE),
  FOREIGN KEY (ID_MEDICO)   REFERENCES MEDICO   (ID_MEDICO)
);

CREATE TABLE DOCUMENTO_ARCHIVO (
  ID_DOCUMENTO    INT AUTO_INCREMENT,
  TIPO_DOCUMENTO  VARCHAR(50),
  DESCRIPCION     VARCHAR(200),
  ARCHIVO_ADJUNTO VARCHAR(255),
  FECHA           DATE,
  ID_PACIENTE     INT,
  PRIMARY KEY (ID_DOCUMENTO),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE)
);

CREATE TABLE MEDICACION_TRATAMIENTO (
  ID_MEDICACION INT AUTO_INCREMENT,
  NOMBRE        VARCHAR(100) NOT NULL,
  DOSIS         VARCHAR(50),
  FRECUENCIA    VARCHAR(50),
  DURACION      VARCHAR(50),
  FECHA_INICIO  DATE,
  FECHA_FIN     DATE,
  ID_PACIENTE   INT,
  PRIMARY KEY (ID_MEDICACION),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE)
);

CREATE TABLE FACTURA_PAGO (
  ID_FACTURA           INT AUTO_INCREMENT,
  FECHA                DATE NOT NULL,
  CONCEPTO             VARCHAR(200),
  MONTO                DECIMAL(10,2),
  ESTADO_PAGO          VARCHAR(30),
  DETALLES_TRANSACCION TEXT,
  ID_PACIENTE          INT,
  PRIMARY KEY (ID_FACTURA),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE (ID_PACIENTE)
);
